name: Build for Mac and Linux

on:
  push:
    branches:
      - main  # Adjust as necessary

jobs:
  build:
    runs-on: macos-latest  # For macOS, or use ubuntu-latest for linux

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Adjust to your Python version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile --windowed --icon=logo_pepin_icon.ico mails_Pépin_app.py

      - name: Upload the built application
        uses: actions/upload-artifact@v2
        with:
          name: built-application
          path: dist/  # Path to the generated executables
